version: '3'
services:
  employee-db:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: employee-db
    volumes:
      - ./data:/var/lib/postgresql/data